spring:
  application:
    name: matricula-ufsc-app
  # ===============================
  # = BANCO DE DADOS
  # ===============================
  jpa:
    show-sql: ${SHOW_SQL}
    generate-ddl: ${GENERATE_DDL}
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true

# ===============================
# = APLICAÇÃO
# ===============================
app:
  jwt-secret: ${JWT_SECRET}
  firebase-credentials: ${CREDENTIALS}
  allowed-origin: ${ALLOWED_ORIGIN}
  matricula:
    carga-horaria:
      min: ${CARGA_HORARIA_MINIMA}
      max: ${CARGA_HORARIA_MAXIMA}
