spring:
  application:
    name: matricula-ufsc-app
  # ===============================
  # = BANCO DE DADOS
  # ===============================
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true

# ===============================
# = APLICAÇÃO
# ===============================
app:
  jwt-secret: ${JWT_SECRET}
  firebase-credentials: ${CREDENTIALS}
