spring:
  application:
    name: matricula-ufsc-app
  # ===============================
  # = BANCO DE DADOS
  # ===============================
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true

# ===============================
# = APLICAÇÃO
# ===============================
app:
  jwt:
    secret: ${JWT_SECRET}
  firebase-configuration:
    project-id: ${PROJECT_ID}
    private-key-id: ${PRIVATE_KEY_ID}
    private-key: ${PRIVATE_KEY}
    client-email: ${CLIENT_EMAIL}
    client-id: ${CLIENT_ID}
    token-uri: ${TOKEN_URI}
    credentials: ${CREDENTIALS}
